### ISSUE TITLE
As a SounderSIPS user, i want to build an application package automatically from within the Unity system

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-ads-deployment#82] opened 2023-01-20 22:23 UTC
Acceptance Criteria:

* Unity users can build an applicaiton package
* Application package contains ...
  - metadata file outputs (for use in catalogging via U-DS)
  - Input/Output characterizations
  - WPS-T definition

**Comment by mcduffie** [comment] 2023-04-12 17:35
Duplicate of [unity-project-management #67](https://github.com/unity-sds/unity-project-management/issues/67)

**Closed by mcduffie** 2023-04-12 17:35 UTC
Labels: Epic
